env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
parser: '@typescript-eslint/parser'
settings:
  import/resolver:
    typescript: {}
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/explicit-module-boundary-types':
    - off
  '@typescript-eslint/no-empty-interface':
    - off
