export const TYPES = {
  Db: Symbol('Db'),
  KafkaProducer: Symbol('KafkaProducer'),
  KafkaConsumer: Symbol('KafkaConsumer'),
  RedisSubscriber: Symbol('RedisSubscriber'),
  Redis: Symbol('Redis'),
  EventBus: Symbol('EventBus'),
  CommandBus: Symbol('CommandBus'),
  QueryBus: Symbol('QueryBus'),
  CommandHandler: Symbol('CommandHandler'),
  QueryHandler: Symbol('QueryHandler'),
  Event: Symbol('Event'),
  EventHandler: Symbol('EventHandler'),
  EventStore: Symbol('EventStore'),
  ApplicationRepository: Symbol('ApplicationRepository'),
  ApplicationEventStore: Symbol('ApplicationEventStore'),
  GetAllApplicationsQueryHandler: Symbol('GetAllApplicationsQueryHandler'),
  ApiServer: Symbol('ApiServer'),
};
